baseURL: "https://annsopirate.github.io/"
languageCode: "en-us"
title: "Hovart Anne-Sophie - Portfolio"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: true

  favicon: "/images/icon.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  #customMenus:
    #- name: "Blog"
      #Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/moi.png"
  name: "Anne-Sophie Hovart"
  namecolor: ffc107
  profession: "Récemment diplômée d'une Licence Professionnelle CréaWeb et à la recherche d'un emploi"
  github: "https://github.com/annsopirate"
  #gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/anne-sophie-hovart/"
  #twitter: "https://twitter.com/"
  #instagram: "https://instagram.com/"
  #facebook: "https://facebook.com"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "🌈 Heyyy ! Moi c'est Anne-Sophie, j'ai 20 ans, je suis en ce moment à la recherche d'un emploi. J'ai validé (avec la mention bien) ma LP CréaWeb que j'ai effectuée à l'IUT de Lens. J'ai dernièrement effectué mon alternance durant 9 mois dans la [Croquante](https://croquante.fr/) agence de communication et créatrice de site internet."
  descripe_l2_person: "💖 Ce qui me plaît c'est le graphisme, le design et le développement web front-end ! J'ai découvert ce type de développement lors de ma première année de DUT informatique et lors de mon année de licence, je compte en apprendre davantage sur le graphisme."
  descripe_l3_person: "🎨 À part ça, le dessin, la peinture, la photographie, la lecture et les Rubik's Cube sont mes passe-temps favoris !"
  descripe_l4_person: "📕 Ce que je lis en ce moment : Harry Potter et la coupe de feu."
  descripe_l5_person: "🧊 Mon Rubik's Cube favori : le Megaminx."
  descripe_l6_person: "Tu veux voir les projets que j'ai réalisés ? clique [ici](#projects) !"


  skills:
    - name: Markdown
    - name: HTML/CSS
      percentage: 80
    - name: SQL
      percentage: 80
    - name: Bash
      percentage: 70
    - name: Hugo
      percentage: 60
    - name: Python
      percentage: 50
    - name: PHP
      percentage: 40
    - name: Typescript / Javascript
      percentage: 40
    - name: Java
      percentage: 40
        

  # Experience
  disable_experience: false
  experience:
    - company: "Google"
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "Licence Professionnelle"
      branch: "CréaWeb"
      university: "IUT de Lens"
      startedyear: "2022"
      graduation: "2023"
    - degree: "DUT"
      branch: "Informatique"
      university: "IUT de Lens"
      startedyear: "2020"
      graduation: "2022"
    - degree: "BAC S"
      branch: "Spé mathématiques"
      university: "Lycée Arthur Rimbaud"
      startedyear: "2019"
      graduation: "2020"

  # Projects
  disable_projects: false
  projects:
    - name: "UI Challenge"
      date: "> Février 2023"
      img: /images/uichallenge.png
      githublink: ""
      featuredlink: "https://www.figma.com/file/mL4zjnQUlTchybndTvSOuZ/D%C3%A9fis?type=design&node-id=28%3A151&t=7gdI8q466Gu3q3iH-1"
      description: 'Défi 1 : écran de connexion - 45 minutes ——
      Défi 2 : écran de réglage de température - 1h30 ——
      Défi 3 : widget de player de musique - 30 minutes ——
      Défi 4 : écran de choix de pricing - 1h'
  
    - name: "Maquettes du site Coatle"
      date: "> Octobre 2022"
      img: /images/coatle.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/TsEP7UFYoXR5UeP1H7zHjf/Exercice-3---Design-Web?page-id=0%3A1&node-id=7-155&starting-point-node-id=7%3A155&scaling=scale-down"
      description: "J'ai réalisé la page d'accueil et la page produit d'un site fictif vendant du chocolat."
      
    - name: "Maquette d'une application de streaming musical"
      date: "> Octobre 2022"
      img: /images/musicapp.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/eMq1QyXQTC0NUFK5JuD49A/Exercice-2---Design-Web?page-id=0%3A1&node-id=1%3A2&viewport=397%2C167%2C0.04&scaling=scale-down&starting-point-node-id=1%3A2"
      description: "Ceci est la première maquette que je réalise avec Figma. En cliquant sur le lien, vous aurez accès au prototype."
    
    - name: "Création d'un Burger Quiz en Typescript"
      date: "> Avril 2022"
      img: /images/burgerquiz.PNG
      githublink: ""
      description: "En équipe de 6, nous avons dû réaliser un site internet en Angular, reprenant le concept du Burger Quiz. Pendant deux jours, nous avons travaillé comme si nous étions en entreprise, en suivant la méthode Agile."
      
    - name: "Portfolio"
      date: "> Novembre 2021 -  | Projet pour mes études"
      img: /images/portfo.png
      githublink: "https://github.com/annsopirate/Portfolio"
      featuredlink: "/"
      description: "Création de mon portfolio à l'aide du logiciel Hugo. Grâce à ce projet, j'ai appris à utiliser Hugo correctement et en profondeur !"

    - name: "Projet Web en 48 heures top chrono !"
      date: "> Décembre 2021"
      img: /images/prjtmarathon.png
      githublink: "https://github.com/annsopirate/Projet_Marathon"
      description: "Le \"Projet Marathon\" consistait en la réalisation d'un site de gestion de séries télévisées. Mes deux camarades et moi avons fait équipe avec 3 étudiants en DUT MMI. Nous avons réalisé le back-end et eux le front."


    - name: "Site de l'entreprise XavPC"
      date: "> Été 2021 | Projet personnel"
      img: /images/xavpc.PNG
      featuredlink: "http://xavpc.free.fr/"
      description: "Création de la version 3 du site de l'enteprise XavPC en HTML / CSS. Pour m'entraîner pendant les vacances, j'ai voulu refaire entièrement ce site avec les connaissances acquises en première année."

    - name: "Portail national des IUT informatique"
      date: "> Novembre 2020 - Janvier 2021 | Projet pour mes études"
      img: /images/PNIUTI.PNG
      githublink: "https://github.com/annsopirate/projet_tutore_sem1"
      featuredlink: "https://blurryfoxer.github.io/accueil/accueil.html"
      description: "Nous avons dû, en équipe de trois, refaire le portail national des IUT informatique en HTML / CSS. Ça a été mon projet favori de ma première année."



  # Achievements
  disable_achievements: false
  achievements:
    - title: Projet Voltaire
      description: Obtention du certificat Voltaire avec un total de 848 points.
      img: /images/prjtvol.png
      url: https://mon.certificat-voltaire.fr/verification-certificat?code=AYVGVNV



    - title: CV
      description: Obtenez mon CV en Français.
      img: /images/cv_francais.png
      url: /images/CV_Anne-Sophie_Hovart.pdf

  # Contact
  disable_contact: false
  contact_content: Si vous avez besoin de plus d'informations, vous pouvez me contacter par mail ! Je me ferai un plaisir de vous répondre.
  email: "anne-sophie_hovart@ens.univ-artois.fr"
  
  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
